// ============================================================
// 작품 데이터 파일 — works-data.js
// 새 작품 추가: 아래 블록 하나 복사해서 목록 끝에 붙여넣기
//
// { title: "제목",
//   slug: "url-slug",        ← 추가됨: works.html#slug 형태로 공유됨
//   poster: `이미지URL`,
//   synopsis: `줄거리`,
//   keywords: `#태그1 #태그2`,
//   links: { aladin:"", ridi:"", series:"", kakao:"",
//            kyobo:"", yes24:"", bomtoon:"", bookcube:"", joara:"" } },
// ============================================================

const worksData = [
  { title: "결혼 대신 탈출할게요",
    slug: "sib-bun-ui-o",
    poster: `https://lh3.googleusercontent.com/d/13V7mdYD2WdxprElH1EAncNbh0VPbgUKT`,
    synopsis: `플로리안의 공주 루디스는 카르타와 전쟁 중인 조국을 지원한다는 조건으로 세이브리아의 왕태자 토리스와 약혼을 맺는다.루디스가 성년이 되는 생일에 결혼식을 올리기로 약속하고 그때만을 기다리던 어느 날, 왕태자는 플로리안에 승산이 없음을 주장하며 조약을 손바닥 뒤집듯 저버리고 막무가내로 루디스와의 결혼을 추진한다.결혼을 거부하는 루디스를 왕태자는 강제로 탑에 연금한다. 루디스는 이 결혼에서 벗어나고, 세이브리아의 배신을 조국에 알리기 위해 탈출을 결행하던 중, 바첸 판이라는 소년을 만나게 되는데….아름다운 꽃의 나라 플로리안. 루디스는 과연 조국의 평화를 지켜낼 수 있을까?`,
    keywords: `#로맨스판타지 #서양 #근세 #궁정물 #판타지 #왕족 #공주 #황제 #정령 #사랑꾼남 #순정남 #존댓말남 #왕족/귀족녀 #외유내강 #직진녀 #정략결혼 #오해/착각 #쌍방삽질 #초월적존재 #나이차커플 #불멸 #마법 #해피엔딩 #여주중심 #첫사랑 #능력남 #다정남`,
    links: { aladin: "", ridi: "https://ridibooks.com/books/4614000150", series: "", kakao: "", kyobo: "", yes24: "", bomtoon: "", bookcube: "", joara: "" } },

  { title: "십 분의 오",
    slug: "sib-bun-ui-o",
    poster: `https://lh3.googleusercontent.com/d/1Rz5yGPfyCqEK--KzoGhbSSJUeLTeuBwo`,
    synopsis: `스튜디오 소속 드라마 기획 PD인 정현진은 우연히 자신의 첫사랑이자 짝사랑인 차민영을 마주한다. 함께 보낸 하룻밤, 그것으로 끝나리라 생각한 관계는 차민영이 스튜디오 모회사 본부장으로 부임하면서 깊이 얽히기 시작하는데....`,
    keywords: `#현대물 #GL/백합 #로맨틱코미디 #오피스물 #사회인 #방송계 #재벌녀 #금수저 #영앤리치 #방송국 #PD #연상공 #능력공 #재벌공 #후회공 #상처공 #연하수 #평범수 #다정수 #외유내강 #집안사정 #재회 #동창 #선후배 #성장 #구원 #첫사랑 #트라우마 #피아노 #직장인로맨스 #나이차커플 #갑을관계 #선섹후사`,
    links: { aladin: "http://aladin.kr/p/JS2Ej", ridi: "https://ridibooks.com/books/4614000147", series: "", kakao: "", kyobo: "https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000013096507", yes24: "https://m.yes24.com/goods/detail/191298052", bomtoon: "", bookcube: "https://www.bookcube.com/book/m/detail.asp?series_num=926041071", joara: "" } },

  { title: "예외의 법칙",
    slug: "yeouiui-beopchik",
    poster: `https://lh3.googleusercontent.com/d/1hFg73VHwiCxB_iSmF056916idyL9gluq`,
    synopsis: `시야에 들어온 사람을 제 생각대로 움직이게 할 수 있는 신기한 능력을 가진 서이진.\n\n제약회사 영업사원으로 오늘도 근면 성실하게 일하는 그녀의 앞에 처음으로 제 능력이 통하지 않는 상대, 하루 약국의 약사 이유안이 나타난다.\n\n사람을 대하는 게 한없이 서투른 이진은 과연 제 인생 최초의 예외를 어떻게 극복해 나갈 것인가?`,
    keywords: `#GL/백합 #현대물 #오피스물 #일상물 #사회인 #직장인\n#메디컬 #제약회사 #영업사원 #약사 #달달물 #초능력 #갑을관계 #오해/착각\n#미인공 #연하공 #잔망공 #능글공 #연상수 #얼빠수 #단정수 #상처수`,
    links: { aladin:"https://t.co/vGZmtuPv8z", ridi:"https://ridibooks.com/books/4614000145", series:"https://m.series.naver.com/novel/detail.series?productNo=14077158", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000012944579", yes24:"https://m.yes24.com/goods/detail/189004728", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=926028407", joara:"" } },

  { title: "어떤 우정은",
    slug: "eotteon-ujeong-eun",
    poster: `https://lh3.googleusercontent.com/u/0/d/10AG2cGm383jzxd3XoCSn0sUkN7T4nDu1`,
    synopsis: `오랜 친구 사이로 지내온 하린과 나연. 하린은 친구인 나연을 십여 년간 짝사랑해왔지만, 차마 고백하지는 못한다.\n\n그렇게 체념하며 살아가다 결혼 적령기를 맞은 나연의 결혼 선언으로 하린은 선택의 기로에 선다.`,
    keywords: `#현대물 #학원물 #캠퍼스물 #GL/백합 #고등학생 #대학생 #전학생 #사회인 #전문직\n#헤테로 #헤녀 #순정녀 #다정녀 #직진녀 #쾌활발랄녀 #댕댕녀 #상처녀 #애교녀 #짝사랑녀 #동갑내기\n#짝사랑 #삽질 #성장 #힐링 #현실연애 #동갑커플 #친구>연인 #달달물 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/PS4Zy", ridi:"https://t.co/h2NeCr6drn", series:"https://m.series.naver.com/novel/detail.series?productNo=13967810", kakao:"", kyobo:"https://t.co/HPh3HSHM97", yes24:"https://t.co/ZiF66SXGfN", bomtoon:"", bookcube:"https://t.co/v6SXHDjS8i", joara:"" } },

  { title: "시한부 공녀님의 마지막 여행",
    slug: "sihanbu-gongnyeonim-majimak-yeohaeng",
    poster: `https://drive.google.com/thumbnail?id=18KIb0BBPGwgp9YG6n6pC3qJQyjxL36Bq&sz=s4000`,
    synopsis: `원래는 남작 영애였으나 지금은 용병인 넬리카 프린은 병약한 귀공녀 아델라 레오나드의 임시 호위로 고용된다. 마력 과다증이라는 희소병을 앓는 아델라는 언제 갑자기 죽을지 모르는 운명이다. 두 사람은 철저히 고용주와 고용인의 관계를 유지하지만, 여정을 함께하면서 서로에게 애틋한 마음을 품게 된다.`,
    keywords: `#GL/백합 #가상시대물 #판타지물 #서양풍 #왕족/귀족 #기사 #여기사 #용병 #아가씨 #마법사 #시한부 #애잔 #재회 #여행 #계약관계 #신분차이 #달달 #순애 #성장 #능력녀 #첫사랑 #비밀연애`,
    links: { aladin:"http://aladin.kr/p/oEo5Zv", ridi:"https://ridibooks.com/books/4614000140", series:"https://m.series.naver.com/novel/detail.series?productNo=13564030", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000012372920", yes24:"https://m.yes24.com/goods/detail/172002425", bomtoon:"", bookcube:"", joara:"" } },

  { title: "솔티드 카라멜 초콜릿",
    slug: "salted-caramel-chocolate",
    poster: `https://drive.google.com/thumbnail?id=1XMZzlLelebd4ubjqOAf3qVnZszcn0RZi&sz=s4000`,
    synopsis: `대학생 이윤송은 옆집 언니였고, 지금은 동거인 중인 권세민을 무려 9년째 짝사랑 중이다.\n어느 날, 세민 본인도 모르는 변화를 눈치챈 윤송은 짝사랑을 끝내기 위한 계획을 세운다. 바로 세민을 꼬실 계획.`,
    keywords: `#GL/백합 #현대물 #로맨틱코미디 #대학생 #직장인 #사회인 #이웃사촌 #연하공 #잔망공 #계략공 #연상수 #순진수 #달달 #해피엔딩 #힐링물`,
    links: { aladin:"http://aladin.kr/p/pE6hu", ridi:"https://ridibooks.com/books/4614000139", series:"https://m.series.naver.com/novel/detail.series?productNo=13449128", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000012242741", yes24:"https://m.yes24.com/goods/detail/167572812", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925055437", joara:"" } },

  { title: "오류 해결을 바라신다면",
    slug: "oryu-haegyeol-barasin-damyeon",
    poster: `https://drive.google.com/thumbnail?id=1YAL2aAanD03L3G4nCrRoOP_S3MKpQNdL&sz=s4000`,
    synopsis: `백의정은 유일한 친구 한진솔을 짝사랑한다. 가망 없는 애정을 끝내기로 마음먹은 의정은 고등학교 졸업식을 진솔에게서 떠날 디데이로 삼는다.\n그러나 다짐이 우습게도, '오류', '특기자' 등 낯선 것들이 불쑥 나타나 둘의 목숨을 위협한다.`,
    keywords: `#GL/백합 #현대물 #판타지물 #센티넬버스 #가이드버스 #학원물 #오피스물 #고등학생 #직장인 #사회인 #성장물 #친구>연인 #달달 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/fC2Cq", ridi:"https://ridibooks.com/books/4614000134", series:"https://m.series.naver.com/novel/detail.series?productNo=13246687", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000012057797", yes24:"https://m.yes24.com/goods/detail/159491112", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925047005", joara:"" } },

  { title: "러브 익셉션(Love Exception)",
    slug: "love-exception",
    poster: `https://drive.google.com/thumbnail?id=1uuRpE3DqrHQcKprylnUyGDAlouPiEAul&sz=s4000`,
    synopsis: `세상을 바꿀 앱을 개발한 IT스타트업의 CEO, 천재 프로그래머 강이현. 대기업과의 지식재산권 분쟁에 휘말린 그의 앞에 대형 법무법인의 냉철한 엘리트 변호사 차윤찬이 구원자처럼 등장한다.`,
    keywords: `#현대물 #오메가버스 #달달물 #첫사랑 #미인공 #연하공 #다정공 #순진공 #미남수 #연상수 #일상물`,
    links: { aladin:"http://aladin.kr/p/zCHUS", ridi:"https://ridibooks.com/books/4614000129", series:"https://m.series.naver.com/novel/detail.series?productNo=13137652", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000011991179", yes24:"https://m.yes24.com/goods/detail/154562492", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925043961", joara:"" } },

  { title: "다시는 사랑에 빠지지 않는 방법",
    slug: "dasineun-sarange-bbajiji-anhneun-bangbeop",
    poster: `https://drive.google.com/thumbnail?id=1R4SNxZUP47oWzi65Mlvv2gtNwougZ61B&sz=s4000`,
    synopsis: `아이돌 걸그룹 스타클의 멤버 주파랑. 두 번에 걸친 연애가 전부 실패로 끝난 파랑은 다시는 사랑에 빠지지 않겠노라 다짐한다.\n그러나 다짐을 놀리듯, 레나타 한 플로레스가 나타난다.`,
    keywords: `#현대물 #GL/백합 #연예계물 #운동선수 #농구선수 #가수 #아이돌 #걸그룹 #교포 #용병 #직진공 #다정공 #걸크러시 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/RCCCE", ridi:"https://ridibooks.com/books/4614000132", series:"https://m.series.naver.com/novel/detail.series?productNo=13090862", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000011895733", yes24:"https://m.yes24.com/goods/detail/153120157", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925040983", joara:"" } },

  { title: "수상한 최 과장",
    slug: "susanghan-choe-gwajang",
    poster: `https://drive.google.com/thumbnail?id=1l6Rcc0MxmJPk2VeYREhRe54Fr5LjxlsG&sz=s4000`,
    synopsis: `한백대학교 학생처에서 근무하는 34살 김의진. 까칠한 직속 상사 최수인(과장, 나이 미상, 예쁨)과 사사건건 부딪치며 하루 하루 힘겨운 생활을 이어간다.`,
    keywords: `#현대물 #오피스물 #GL/백합 #교직원 #대학교 #상사 #부하 #연상공 #연하수 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/2RAGb", ridi:"https://ridibooks.com/books/4614000125", series:"https://naver.me/5R4OK5Ce", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000011507329", yes24:"https://m.yes24.com/goods/detail/147337545", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925024240", joara:"" } },

  { title: "이름 없는 기억",
    slug: "ireum-eomneun-gieok",
    poster: `https://drive.google.com/thumbnail?id=15269j6eaNYzEMBQcNdkGAaVGu6Rmcc0L&sz=s4000`,
    synopsis: `고교 1학년 여름방학이 끝나고 서연 여고로 전학을 온 서재희. 전학생의 예쁜 외모에 눈길이 끌린 공태린은 사소한 오해를 겪어가면서 재희와 가까워지고, 두 사람은 '좋아함'을 넘어선 감정을 자각하게 된다.`,
    keywords: `#현대물 #학원물 #캠퍼스물 #GL/백합 #고등학생 #대학생 #전학생 #기억상실 #재회 #달달물 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/kRi5r", ridi:"https://ridibooks.com/books/4614000121", series:"https://series.naver.com/novel/detail.series?productNo=12582492", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000011437381", yes24:"https://www.yes24.com/product/goods/146954943", bomtoon:"", bookcube:"https://www.bookcube.com/detail.asp?series_num=925022143", joara:"" } },

  { title: "나를 경멸하는 당신에게 바치는 연서",
    slug: "nareul-gyeongmelhaneun-dangsinhante-bachineun-yeonseo",
    poster: `https://drive.google.com/thumbnail?id=1imzykkGzxZyN3Yq6oHxsAIEwCTnsEP5S&sz=s4000`,
    synopsis: `신의 뜻에 따라 세워진 알페르니아 성국. 성국의 기사로 살아가던 디아넬 엘라파는 어느 귀족의 파티에 경호 인력으로 동원되었다가 물에 빠진 귀족 영애 리브카 메리를 구한다.`,
    keywords: `#GL/백합 #가상시대물 #판타지물 #서양풍 #근대 #서간체 #기사 #여기사 #힐링물 #첫사랑 #재회 #달달`,
    links: { aladin:"http://aladin.kr/p/wqVVG", ridi:"https://ridibooks.com/books/4614000103", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000008617854", yes24:"https://m.yes24.com/Goods/Detail/132560466", bomtoon:"", bookcube:"https://me2.do/GfCMM3kK", joara:"" } },

  { title: "김산산전",
    slug: "kim-sansan-jeon",
    poster: `https://drive.google.com/thumbnail?id=1hpOOrxZG_7sj5S8zIsMYeRqRednTdTEQ&sz=s4000`,
    synopsis: `경기도 양주골의 천한 노비 산산이. 그녀가 소중하게 생각하는 것은 서양인의 핏줄을 가진, 노란 머리를 한 아가씨 권유라뿐이다.`,
    keywords: `#시대물 #가상시대물 #역사물 #GL/백합 #판타지 #동양풍 #액션 #조선 #주종관계 #신분차이 #성장`,
    links: { aladin:"http://aladin.kr/p/nzvBx", ridi:"https://ridibooks.com/books/4614000118", series:"https://m.series.naver.com/novel/detail.series?productNo=12367042", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000011239770", yes24:"https://m.yes24.com/goods/detail/144160609", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925012925", joara:"" } },

  { title: "완벽한 계획에 그녀들이란 변수",
    slug: "wanbyeokhan-gyehoeke-geunyeodeul-byeonsu",
    poster: `https://drive.google.com/thumbnail?id=1vTYzJgJd_UI0-t9eJFjKv0rYaQofaWlM&sz=s4000`,
    synopsis: `대한민국이 낳은 세계적인 가수 아로하. 해외 투어를 마치고 귀국을 앞둔 어느 밤, SNS에 공개적으로 커밍아웃을 한다.`,
    keywords: `#현대물 #GL #백합 #연예인 #가수 #아이돌 #삼각관계 #다각관계 #커밍아웃 #성장`,
    links: { aladin:"http://aladin.kr/p/dRKmf", ridi:"https://t.co/2b2DE20bec", series:"https://t.co/YGy8iRQs1o", kakao:"", kyobo:"https://t.co/wjbQ0SJr9p", yes24:"https://t.co/8OYHf1y0S1", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925003435", joara:"" } },

  { title: "몇 번이나 바랐을까",
    slug: "myeot-beona-baradeulkka",
    poster: `https://drive.google.com/thumbnail?id=1HQEoVXE5Hp9Sgb9qkb4UfnsB88DLW4dp&sz=s4000`,
    synopsis: `9년 전, 여자 친구와 함께 뜻하지 않게 살인현장을 목격하게 된 이채은. 범인 중의 하나가 경찰이라는 사실을 알고 추적을 피해 잠적한다.`,
    keywords: `#GL/백합 #현대물 #느와르 #범죄물 #수사물 #경찰/형사 #재회 #복수 #트라우마 #스릴러`,
    links: { aladin:"http://aladin.kr/p/eR2wz", ridi:"https://ridibooks.com/books/4614000113", series:"https://m.series.naver.com/novel/detail.series?productNo=12053196", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000010829830", yes24:"https://m.yes24.com/Goods/Detail/141226390", bomtoon:"", bookcube:"https://www.bookcube.com/book/m/detail.asp?series_num=925000459", joara:"" } },

  { title: "여름의 숲은 푸르다",
    slug: "yeoreum-soop-eun-pureuda",
    poster: `https://drive.google.com/thumbnail?id=1BaNwRnFiyLvn_ogpHtYl7skzqaQxl2tS&sz=s4000`,
    synopsis: `자신의 오빠와 결혼해 곧 새언니가 될 서여름. 그런 여름을 남몰래 짝사랑하는 이청림. 자신을 향한 청림의 감정을 이미 아는 여름은 청림과 결혼하겠다는 선언을 한다.`,
    keywords: `#GL/백합 #현대물 #사회인 #금수저 #정략결혼 #선결혼후연애 #달달 #일상`,
    links: { aladin:"https://t.co/byvrPXTafz", ridi:"https://ridibooks.com/books/4614000111", series:"https://m.series.naver.com/novel/detail.series?productNo=11662766", kakao:"", kyobo:"", yes24:"https://m.yes24.com/Goods/Detail/134200348", bomtoon:"", bookcube:"https://me2.do/xk1FFClT", joara:"" } },

  { title: "암실",
    slug: "amshil",
    poster: `https://drive.google.com/thumbnail?id=1dv1D7ado-EtVBzCKjRAMYG-8CUWbNs9T&sz=s4000`,
    synopsis: `마약상을 잡기 위해 논현동의 한 명품 셀렉샵에 아르바이트로 위장하여 잠복근무를 하게 된 형사 은수. 그런 은수의 곁에 4명의 여자들이 모여든다.`,
    keywords: `#GL/백합 #현대물 #느와르 #추리/미스터리물 #수사물 #마약 #스릴러 #반전`,
    links: { aladin:"http://aladin.kr/p/hq0lf", ridi:"https://ridibooks.com/books/4614000108", series:"https://series.naver.com/novel/detail.series?productNo=11588742", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000008855391", yes24:"https://www.yes24.com/Product/Goods/133630655", bomtoon:"", bookcube:"https://me2.do/FUhPKE8A", joara:"" } },

  { title: "조선시대 막장소설가로 깨어났다",
    slug: "joseon-makjang-soselgaro-kkaeeonatda",
    poster: `https://drive.google.com/thumbnail?id=19J7P_rl-ZT20OM7HcVXJcS64jWK2ekLD&sz=s4000`,
    synopsis: `대학원에서 고전문학을 연구하는 대학원생 이수진은 귀갓길에 트럭 사고를 당해 정조 치하의 조선시대로 타임슬립한다.`,
    keywords: `#로맨스 #가상시대물 #판타지물 #회귀물 #조선시대 #회귀/타임슬립 #소설가 #달달 #퓨전사극`,
    links: { aladin:"http://aladin.kr/p/3qA8p", ridi:"https://ridibooks.com/books/4614000105", series:"https://series.naver.com/novel/detail.series?productNo=11560772", kakao:"https://page.kakao.com/content/64988918", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000008861925", yes24:"https://www.yes24.com/Product/Goods/133231140", bomtoon:"", bookcube:"https://me2.do/5mIhsHrA", joara:"" } },

  { title: "마치 기적과도 같은",
    slug: "machi-gijeok-gateun",
    poster: `https://drive.google.com/thumbnail?id=17y8LsXQDJX4HRKmTtXMmz_ouP1uYAuWd&sz=s4000`,
    synopsis: `어느 봄, 온희는 기적으로 백시운을 살려낸다. 대대로 기적을 일으키는 왕가의 둘째 공주 온희는 오랜 시간 기적을 일으키지 못했다.`,
    keywords: `#GL/백합 #현대물 #판타지물 #궁중물 #입헌군주제 #대학생 #공주 #군인 #성장물 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/Kqlnd", ridi:"https://ridibooks.com/books/4614000098", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000008440550", yes24:"https://www.yes24.com/Product/Goods/130034678", bomtoon:"", bookcube:"https://me2.do/xQexj5ye", joara:"" } },

  { title: "어쩔 수 없는 것",
    slug: "eojjeol-su-eomneun-geot",
    poster: `https://drive.google.com/thumbnail?id=1vsXBkhvmm9iPrHUlPMYQi20JZc5w5kaW&sz=s4000`,
    synopsis: `남편이 허름한 모텔에서 목을 매고 자살해 이 세상에서 사라지자, 제희설은 지금껏 모른 척하며 피해왔던 딸 제갈윤과의 관계를 돈독히 하기 위해 다가가기 시작한다.`,
    keywords: `#GL/백합 #현대물 #모녀백합 #고등학생 #유부녀 #가정주부 #모녀관계 #피폐물 #근친물 #성장`,
    links: { aladin:"http://aladin.kr/p/Zq4RF", ridi:"https://ridibooks.com/books/4614000094", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000007646641", yes24:"https://m.yes24.com/Goods/Detail/126679124", bomtoon:"", bookcube:"http://me2.do/5WHYUaR6", joara:"" } },

  { title: "전개가 바뀌지 않아서 장르를 바꾸려고 합니다",
    slug: "jongae-bakkuji-anhaso-jangreul-bakkuryeogo-hamnida",
    poster: `https://drive.google.com/thumbnail?id=1xa7UGD3mzr0CU2gWLu8ATZ9vMz_Yxvqn&sz=s4000`,
    synopsis: `가족에게 학대당해 죽은 주인공은 자신이 읽었던 로맨스 판타지 소설 속의 조연으로 환생한다. 작중에서 민폐 캐릭터로 굴려지던 끝에 항상 비참한 결말을 맞는 자신의 처지를 바꿔보고자 온갖 노력을 기울이지만...`,
    keywords: `#판타지물 #GL/백합 #회귀물 #가상시대물 #서양풍 #정략결혼 #신분차이 #해피엔딩 #결혼엔딩`,
    links: { aladin:"http://aladin.kr/p/AqR3j", ridi:"https://t.co/LAdSJbjscB", series:"", kakao:"", kyobo:"https://t.co/2bXXUv3Fph", yes24:"https://t.co/ZEtoMecVhf", bomtoon:"", bookcube:"https://me2.do/GudXLfqe", joara:"" } },

  { title: "엘리, 그 지긋지긋한 새끼",
    slug: "elli-geut-jigujtjithan",
    poster: `https://drive.google.com/thumbnail?id=1JMD7ryaTzauOczi4K2XvztWsAtk65cAV&sz=s4000`,
    synopsis: `자타공인 퀸즈버드 고등학교의 아이돌, 엘리 램버트. 남녀노소 모두에게 친절한 엘리가 유일하게 태도를 바꾸어 괴롭히는 상대, 비키 아담은 그런 엘리가 못마땅하다.`,
    keywords: `#현대물 #GL/백합 #하이틴로맨스 #학원물 #미국 #고등학생 #인싸 #너드 #소꿉친구 #친구>연인 #결혼엔딩`,
    links: { aladin:"http://aladin.kr/p/gq19I", ridi:"https://ridibooks.com/books/4614000090", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000007354587", yes24:"https://m.yes24.com/Goods/Detail/126025392", bomtoon:"", bookcube:"https://me2.do/xGmJDpVc", joara:"" } },

  { title: "열애소설",
    slug: "yeolae-soseol",
    poster: `https://drive.google.com/thumbnail?id=1L-yTOTs-yhu0wiufwQGxqDyg6n0kM4m6&sz=s4000`,
    synopsis: `집안이 몰락하여 갈 곳이 없어진 정단은 당대의 권세가, 친일파 여첨웅의 집에 정착하게 된다. 그곳에서 만난 여 씨 가문의 아가씨 여온휘.`,
    keywords: `#시대물 #GL/백합 #일제강점기 #아가씨 #하녀 #주종관계 #신분차이 #독립군 #복수 #나이차커플`,
    links: { aladin:"http://aladin.kr/p/EqWEd", ridi:"https://ridibooks.com/books/4614000088", series:"https://series.naver.com/novel/detail.series?productNo=10867571", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000007035853", yes24:"https://www.yes24.com/Product/Goods/125574584", bomtoon:"", bookcube:"https://me2.do/xNmExENB", joara:"" } },

  { title: "근원? 근심!",
    slug: "geunwon-geunsim",
    poster: `https://drive.google.com/thumbnail?id=12xSB3y9OvtGfriICumyKT0S5cxPNCYf-&sz=s4000`,
    synopsis: `강의 출석보다 게임 출석을 성실하게 하는 지유는 온라인 게임 라기오스가 곧 인생이라고 해도 과언이 아닐 정도로 게임에 미쳐있는, 이른바 겜친놈이다.`,
    keywords: `#현대물 #GL/백합 #게임물 #온라인게임 #RPG #길드 #대학생 #고인물 #달달 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/PQMBz", ridi:"https://ridibooks.com/books/4614000085", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000006572335", yes24:"https://m.yes24.com/Goods/Detail/125084470", bomtoon:"", bookcube:"https://me2.do/55RwWtXH", joara:"" } },

  { title: "물 만난 언니",
    slug: "mul-mannan-eonni",
    poster: `https://drive.google.com/thumbnail?id=1xnjNaLvbpUowmmiRBorbycO4J64GaXgk&sz=s4000`,
    synopsis: `올해로 서른. 인생의 분기점을 앞둔 이제희는 소심한 자신을 변화시키고자 요가 학원에 등록하고, 그곳에서 한 여자와 만난다.`,
    keywords: `#GL #백합 #현대물 #사회인 #직장인 #운동 #요가 #수영 #달달 #일상 #직장인로맨스`,
    links: { aladin:"http://aladin.kr/p/vQFh3", ridi:"https://ridibooks.com/books/4614000083", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000006322520", yes24:"https://m.yes24.com/Goods/Detail/124848863", bomtoon:"", bookcube:"https://me2.do/Fm2kjhrA", joara:"" } },

  { title: "네 남편의 조건",
    slug: "ne-nampyeon-jogeon",
    poster: `https://drive.google.com/thumbnail?id=1aefBCpoctJzE-rMKpg9NFyB295uQPkAV&sz=s4000`,
    synopsis: `상처를 주고받아 사랑을 확인해오던 공주윤은 어느 날 한이재에게 다른 남자와의 결혼을 선언한다.`,
    keywords: `#현대물 #GL/백합 #BDSM #사회인 #연예계 #재벌녀 #아이돌 #걸그룹 #결혼엔딩 #나이차커플`,
    links: { aladin:"https://t.co/oeIgkRxTD4", ridi:"https://ridibooks.com/books/4614000080", series:"", kakao:"", kyobo:"https://t.co/kfXy00hZI6", yes24:"https://t.co/R9UYVytfCT", bomtoon:"", bookcube:"https://t.co/fQIlplujdi", joara:"" } },

  { title: "이제 가족이 되겠습니다",
    slug: "ije-gajogi-doegetsseumnida",
    poster: `https://drive.google.com/thumbnail?id=1bX-DeraY6swm9-cEaqmfiR-WKNalT3sz&sz=s4000`,
    synopsis: `에피루스 제국의 귀족 샤리는 평소 불성실한 행실로 인해 뭇 귀족들에게 반감을 사 왔고, 이웃 국가 팔미라에 사절로 보내진다.`,
    keywords: `#GL/백합 #시대물 #가상시대물 #서양풍 #지중해 #로마 #여제 #신분차이 #걸크러시 #동거엔딩`,
    links: { aladin:"http://aladin.kr/p/uQf42", ridi:"https://ridibooks.com/books/4614000078", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005484719", yes24:"https://m.yes24.com/Goods/Detail/123772281", bomtoon:"", bookcube:"https://me2.do/5HtpthBw", joara:"" } },

  { title: "호감도가 보이기 시작했다",
    slug: "hogamdo-boigi-sijakhaetda",
    poster: `https://drive.google.com/thumbnail?id=1eLt-piO0yQu4Sqhs003isHjyBwrzJjaq&sz=s4000`,
    synopsis: `학교 가는 길에 난데없이 '던전'에 휘말린 대학생 백영하. 거대 몬스터와 조우해 헌터로 각성하게 된다. 그러나 얻은 능력은 자신에 대한 상대의 호감도를 확인할 수 있는 '호감도 측정'.`,
    keywords: `#현대물 #판타지물 #GL #백합 #SF #대학생 #헌터 #던전 #다각관계 #하렘 #액션 #성장`,
    links: { aladin:"http://aladin.kr/p/94sTm", ridi:"https://ridibooks.com/books/4614000063", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005304813", yes24:"https://www.yes24.com/Product/Goods/120006158", bomtoon:"", bookcube:"https://me2.do/GnCkbg1g", joara:"" } },

  { title: "두 번째 첫사랑",
    slug: "du-beonjjae-cheossarang",
    poster: `https://drive.google.com/thumbnail?id=1PocYjb7h0a2hTE37sW5ZIkO41k3_61wp&sz=s4000`,
    synopsis: `송지우는 이희원을 짝사랑하지만 끝내 마음을 고백하지 못하고 고등학교를 졸업한다. 8년이 지난 어느 날, 입원한 병원에서 간호사가 된 희원과 재회한다.`,
    keywords: `#현대물 #GL #백합 #간호사 #전문직 #환자 #병원 #첫사랑 #짝사랑 #재회 #달달 #동거엔딩`,
    links: { aladin:"http://aladin.kr/p/E4ZJM", ridi:"https://ridibooks.com/books/4614000075", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005447374", yes24:"https://m.yes24.com/Goods/Detail/123161521", bomtoon:"", bookcube:"https://me2.do/GMWW7m0U", joara:"" } },

  { title: "비커밍 엑스",
    slug: "becoming-x",
    poster: `https://drive.google.com/thumbnail?id=1OEEMSGWBn04pGxNcB6XqbMTcxfE53qi-&sz=s4000`,
    synopsis: `운석 충돌 이후, 절반 이상이 국가로서의 기능을 상실한 2029년의 대한민국. 충돌 당시의 여파로 일부 사람들은 특수한 힘을 갖게 된다.`,
    keywords: `#현대물 #GL #백합 #판타지 #SF #포스트아포칼립스 #가이드버스 #초능력 #나이차커플 #동거엔딩`,
    links: { aladin:"http://aladin.kr/p/B4TYQ", ridi:"https://ridibooks.com/books/4614000072", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005399137", yes24:"https://m.yes24.com/Goods/Detail/122337677", bomtoon:"", bookcube:"https://me2.do/GMW6UvPS", joara:"" } },

  { title: "하멜른의 피리",
    slug: "hamelreun-piri",
    poster: `https://drive.google.com/thumbnail?id=1CuAPSpCPG0SJduuvLHHDz0ZSD_w9lzPa&sz=s4000`,
    synopsis: `다니던 직장을 그만두고 이스트호크에서 패러메딕(응급구조사)으로 일하는 정은우. 어느 날 교통사고 현장에서 크리스라는 여자와 만나고, 사람이 사람을 공격하는 전대미문의 사태가 이스트호크 전역을 덮치는데….`,
    keywords: `#현대물 #GL #백합 #포스트아포칼립스 #좀비물 #응급구조사 #쌍방호감 #서바이벌 #동거엔딩 #해피엔딩`,
    links: { aladin:"http://aladin.kr/p/S4vZl", ridi:"https://ridibooks.com/books/4614000070", series:"https://m.series.naver.com/novel/detail.series?productNo=10107743", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005377752", yes24:"https://m.yes24.com/Goods/Detail/122165350", bomtoon:"", bookcube:"https://me2.do/xvtP7qUH", joara:"" } },

  { title: "백구야, 이리 와",
    slug: "baekguya-iri-wa",
    poster: `https://drive.google.com/thumbnail?id=1TP33N8deoj02grRxlNjj7qrTL0t7hjO-&sz=s4000`,
    synopsis: `갓 입사한 백현아는 자신의 직속상사가 될 팀장과 처음 마주하는 자리에서 그 외모에 시선을 빼앗긴다. 그러나 알고 보니 팀장은 일 폭탄 투척 전문가.`,
    keywords: `#현대물 #GL #백합 #직장인 #재벌녀 #직장상사 #사내연애 #나이차커플 #달달 #동거엔딩`,
    links: { aladin:"http://aladin.kr/p/y40TA", ridi:"https://ridibooks.com/books/4614000067", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005354951", yes24:"https://m.yes24.com/Goods/Detail/121526975", bomtoon:"", bookcube:"https://me2.do/GB5O2PAN", joara:"" } },

  { title: "코스믹라떼",
    slug: "cosmic-latte",
    poster: `https://drive.google.com/thumbnail?id=1aVL7zp3Q_ji8yxpFyV2TWnkAHbrdd-tm&sz=s4000`,
    synopsis: `아이돌 그룹 '포이트 허니'의 멤버 강새아는 어느 날 패스트푸드점 주차장에서 가벼운 접촉사고를 일으킨다. 며칠 후, 카페에서 똑같은 상대에게 또다시 접촉사고를 내고 만다.`,
    keywords: `#현대물 #GL #백합 #직장인 #연예인 #PD #아이돌 #걸그룹 #나이차커플 #비밀연애 #달달`,
    links: { aladin:"http://aladin.kr/p/Gzg8o", ridi:"https://ridibooks.com/books/4614000061", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005160335", yes24:"http://m.yes24.com/Goods/Detail/117093272", bomtoon:"", bookcube:"https://me2.do/FIYP5Pb0", joara:"" } },

  { title: "라스트 트래블",
    slug: "last-travel",
    poster: `https://drive.google.com/thumbnail?id=1Ac8UP80rWqqn39_-C1wH3rd6RN5UnUC6&sz=s4000`,
    synopsis: `두바이 여행을 떠나게 된 대학생 서이안. 도착 한 시간을 남겨두고 갑작스런 기상 악화로 비행기는 어딘가에 불시착한다.\n\n눈을 떠보니, 그곳은 이세계였습니다!?`,
    keywords: `#GL #백합 #판타지물 #가상시대물 #서양풍 #대학생 #황제 #계약관계 #신분차이 #이세계 #달달 #결혼엔딩`,
    links: { aladin:"http://aladin.kr/p/azC9V", ridi:"https://ridibooks.com/books/4614000059", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005138342", yes24:"http://m.yes24.com/Goods/Detail/117859860", bomtoon:"", bookcube:"https://me2.do/xUtOnd8z", joara:"" } },

  { title: "거래-신과 나눈 비밀",
    slug: "georae-sin-gwa-nanun-bimil",
    poster: `https://drive.google.com/thumbnail?id=1H55W6ouMnvnHf-U4BwuyL4uZbJ4ixjFU&sz=s4000`,
    synopsis: `어느 날 수상한 남자 리온과 마주친 신검(神劍) 이반은 후일, 타국의 사절단을 맞이하는 자리에서 그와 다시 만나게 된다.`,
    keywords: `#BL #판타지물 #서양풍 #초월적존재 #전생 #환생 #기억상실 #왕족 #귀족 #애증 #피폐 #애잔`,
    links: { aladin:"http://aladin.kr/p/9QmEt", ridi:"https://ridibooks.com/books/4614000051", series:"", kakao:"", kyobo:"https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005105292", yes24:"http://m.yes24.com/Goods/Detail/117201158", bomtoon:"", bookcube:"https://bit.ly/3RvwxNY", joara:"" } },

  { title: "옆에 누워요",
    slug: "yeope-nuwoyo",
    poster: `https://drive.google.com/thumbnail?id=1cCZmrvcFTlEr3CZ5j-fvYWZScRQZYBnQ&sz=s4000`,
    synopsis: `직장을 그만두고 수험 생활을 시작한 정현은 그 와중에 짝사랑하던 언니의 결혼 소식을 듣게 된다. 가구점에서 일하던 정현 앞에 나타난 검은 모자.`,
    keywords: `#현대물 #GL #백합 #직장인 #인강강사 #수험생 #연하공 #연상수 #나이차커플 #달달 #동거엔딩`,
    links: { aladin:"https://t.co/7c8EJmswf5", ridi:"https://t.co/4E6Pe3289c", series:"", kakao:"", kyobo:"https://t.co/7ss7bi5avV", yes24:"https://t.co/BXcgdblXLx", bomtoon:"", bookcube:"https://bit.ly/3AENa2o", joara:"" } },

  { title: "윗치 퍼펙트",
    slug: "witch-perfect",
    poster: `https://drive.google.com/thumbnail?id=1_SGcqIOf3jCnMFNpCMB_pUSbUp6ctjXq&sz=s4000`,
    synopsis: `마녀들의 고민을 해결해주는 곳 '윗치 퍼펙트'. 그곳을 찾은 마녀, 마여은은 소장으로부터 도무지 이해할 수 없는 수수께끼의 조언을 듣게 된다.`,
    keywords: `#현대물 #로맨틱코미디 #판타지물 #GL #백합 #재벌녀 #호텔 #마녀 #연하공 #연상수 #나이차커플 #하렘`,
    links: { aladin:"http://aladin.kr/p/MQuKQ", ridi:"https://t.co/w9CKGmrsYj", series:"", kakao:"", kyobo:"https://t.co/iXL2QsZtTo", yes24:"https://t.co/mCUS0MXxs3", bomtoon:"", bookcube:"https://bit.ly/3sTTGxV", joara:"" } },

  { title: "true romance",
    slug: "true-romance",
    poster: `https://drive.google.com/thumbnail?id=1Sn1xzwu7FmTL3FNTkEFqt4WoUOo6sluS&sz=s4000`,
    synopsis: `태어나 30년 가까이 연애 경험이라고는 전무한 모태 솔로 정인. 어느 날 변덕스레 떠난 휴가지의 게스트하우스에서 스물두 살의 휴학생 최희원과 만난다.`,
    keywords: `#현대물 #GL #백합 #사회인 #대학생 #체대생 #태권도 #연하공 #연상수 #달달 #나이차커플`,
    links: { aladin:"https://bit.ly/3BWdtRp", ridi:"https://bit.ly/3UIDbBs", series:"", kakao:"", kyobo:"https://bit.ly/3fvnI7Q", yes24:"https://bit.ly/3RqAbHd", bomtoon:"", bookcube:"https://bit.ly/3dXksSf", joara:"" } },

  { title: "고르디우스의 굴레",
    slug: "goreudiuseui-gure",
    poster: `https://drive.google.com/thumbnail?id=1nvn9o4Lh5c0ze6sJmOUkxwUFGhDZfo3g&sz=s4000`,
    synopsis: `알렉산드로스 대왕의 죽음 후, 대왕의 후계자 자리를 둘러싼 싸움이 지중해 곳곳에서 벌어진다. 에피루스의 레다 공주는 나라를 되찾기 위해 이집트의 파라오를 찾아간다.`,
    keywords: `#GL #백합 #시대물 #가상시대물 #서양풍 #고대 #마케도니아 #이집트 #파라오 #정략결혼 #성장`,
    links: { aladin:"http://aladin.kr/p/bf0FQ", ridi:"https://bit.ly/3dTY4Jp", series:"https://bit.ly/3Ck5leM", kakao:"", kyobo:"https://bit.ly/3SiwZ1s", yes24:"https://bit.ly/3SBmPZq", bomtoon:"", bookcube:"https://bit.ly/3Ck5fDW", joara:"" } },

  { title: "시급",
    slug: "sigeup",
    poster: `https://drive.google.com/thumbnail?id=1oPc12gxVd2MpH29qZIjLOGqvpeaVnvdp&sz=s4000`,
    synopsis: `고달픈 인생을 씩씩하게 살아가던 특기자 구차민은 새로운 것을 사랑하는 가이드 안지람을 만난다.\n\n특기자가 맛있고 가이드가 친절합니다.`,
    keywords: `#현대물 #GL #백합 #SF #특기자 #센티넬버스 #가이드 #재벌녀 #흙수저 #나이차커플`,
    links: { aladin:"http://aladin.kr/p/9fedf", ridi:"https://ridibooks.com/books/4614000028", series:"", kakao:"", kyobo:"https://url.kr/jck4i1", yes24:"http://m.yes24.com/Goods/Detail/108442865", bomtoon:"", bookcube:"https://bit.ly/3NgeaKf", joara:"" } },

  { title: "어느 외눈박이에게",
    slug: "eoneu-oennunbagi-ege",
    poster: `https://drive.google.com/thumbnail?id=1mgKaRywzvWmLFxqTHLMQHgLev-Xp4wIM&sz=s4000`,
    synopsis: `서원의 부양자가 된 자기 자신을 믿지 못하고 계속 상처 입히던 이다정은 어느 날, 자신을 떠났던 서원과 다시 마주치게 된다.`,
    keywords: `#현대물 #GL #백합 #SF #부양자 #컬러버스 #재벌녀 #재회물 #성장물 #동갑커플 #쌍방구원`,
    links: { aladin:"http://aladin.kr/p/0f5wb", ridi:"https://t.co/9b617jBwyd", series:"https://t.co/WaLHa4y5Ip", kakao:"", kyobo:"https://t.co/DXVXbfQwq0", yes24:"https://t.co/0sHKhMuGiI", bomtoon:"", bookcube:"https://t.co/grMUA83SIW", joara:"" } },

  { title: "시시때때로",
    slug: "sisitaettaero",
    poster: `https://drive.google.com/thumbnail?id=1yhcPw9p5o1pHVrXp0PnsLdm0DI8KhDWs&sz=s4000`,
    synopsis: `엄마의 죽음 이후 실의에 빠진, 잘 나가는 인강 강사 백단오에게 거대 군수회사 AT는 시간여행이라는 놀라운 제안을 한다.`,
    keywords: `#현대물 #GL #백합 #시간여행 #SF #특수요원 #인강강사 #사내연애 #나이차커플 #동거엔딩`,
    links: { aladin:"http://aladin.kr/p/j4JhE", ridi:"https://ridibooks.com/books/4614000010", series:"", kakao:"", kyobo:"https://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?barcode=480D211119100", yes24:"http://www.yes24.com/Product/Goods/105384389", bomtoon:"", bookcube:"https://bit.ly/3oaeHCW", joara:"" } },

  { title: "가장 완벽한 고백의 밤",
    slug: "gajang-wanbyeokhan-gobak-bam",
    poster: `https://drive.google.com/thumbnail?id=1cr7wOPCNJ-BXIEdOgE6oCAS49VApJuPp&sz=s4000`,
    synopsis: `초중고 동창이지만 같은 대학 같은 과에 와서야 가까워진 치경과 서원. 치경은 중간고사가 끝난 가을밤에 짝사랑하는 서원에게 완벽한 고백을 한다. 그러나 대답을 듣기로 한 다음 날, 최악의 사태가 터지고 마는데….`,
    keywords: `#현대물 #GL #백합 #대학교 #대학생 #좀비 #좀비물 #재난물 #짝사랑 #쌍방호감 #생존로맨스`,
    links: { aladin:"http://aladin.kr/p/EP6Hh", ridi:"https://ridibooks.com/books/4614000033", series:"http://naver.me/GG4ZHlbz", kakao:"", kyobo:"https://han.gl/fXtlB", yes24:"http://m.yes24.com/Goods/Detail/109779803", bomtoon:"", bookcube:"https://bit.ly/3NC6hxX", joara:"" } },

  { title: "사랑이 스미는 중",
    slug: "sarangi-seumineun-jung",
    poster: `https://drive.google.com/thumbnail?id=181wWH-H0PMutyu27Q63tUuhP83k1vfw4&sz=s4000`,
    synopsis: `선화는 오랜 연인인 제은이 변했다는 것을 느낀다. 제은이 떠난 후 글쓰기를 재개하면서 자신을 늘 응원하던 독자인 '왕큰숲'에게 인간적인 호감을 가진다.`,
    keywords: `#현대물 #GL #백합 #직장인 #소설작가 #독자 #연상수 #연하공 #나이차커플 #동거엔딩`,
    links: { aladin:"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=292317125", ridi:"https://ridibooks.com/books/4614000031", series:"", kakao:"", kyobo:"https://m.kyobobook.co.kr/digital/ebook/ebookContents.ink?barcode=4812204220087", yes24:"http://m.yes24.com/Goods/Detail/108942821", bomtoon:"", bookcube:"https://bit.ly/3Mpe1TG", joara:"" } },

  { title: "첫사랑",
    slug: "cheossarang",
    poster: `https://drive.google.com/thumbnail?id=1WmEi8zhCaYihaH_2X6Aam5DSvWyfM0kf&sz=s4000`,
    synopsis: `지영은 중학교 첫 등교날 마주한 도경에게 알 수 없는 감정을 느낀다. 지겨운 첫사랑의 끝, 두 사람은 사랑을 시작한다.`,
    keywords: `#현대물 #GL #백합 #고등학생 #대학생 #청소년 #인싸 #아싸 #따돌림 #연상공 #연하수 #첫사랑 #짝사랑`,
    links: { aladin:"http://aladin.kr/p/Cffgs", ridi:"https://ridibooks.com/books/4614000027", series:"", kakao:"", kyobo:"http://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?barcode=480D220317300", yes24:"http://www.yes24.com/Product/Goods/108232775", bomtoon:"", bookcube:"https://bit.ly/3qcTw3M", joara:"" } },

  { title: "첫사랑 고득점 N제",
    slug: "cheossarang-godeukjeom-nje",
    poster: `https://drive.google.com/thumbnail?id=1IZlfh92ogWkkIph4PV5WgPt21m59awIO&sz=s4000`,
    synopsis: `최악의 하루라고 생각했던 날, 문하린은 절교한 소꿉친구 김은주와 재회한다. 원래도 조금 껄렁하기는 했지만 치마까지 줄이고 향수도 뿌린 은주가 하린은 낯설기만 하다.`,
    keywords: `#현대물 #GL #백합 #고등학생 #외고 #고3 #대학생 #모범생 #소꿉친구 #입시 #수능 #하이스쿨로맨스`,
    links: { aladin:"http://aladin.kr/p/GfZBV", ridi:"https://ridibooks.com/books/4614000020", series:"", kakao:"", kyobo:"https://m.kyobobook.co.kr/digital/ebook/ebookContents.ink?barcode=480D220219870", yes24:"http://www.yes24.com/Product/Goods/107679326", bomtoon:"", bookcube:"https://m.kyobobook.co.kr/digital/ebook/ebookContents.ink?barcode=480D220219870", joara:"" } },

  { title: "그해 여름",
    slug: "geuhae-yeoreum",
    poster: `https://drive.google.com/thumbnail?id=1PcfmsWIi4rJk4km3Iv4TMIu6_ZOPCBeZ&sz=s4000`,
    synopsis: `사랑 따위 아이스크림보다도 못하고 밥 먹여주지도 않는다고 믿었던 질풍노도의 고삼, 국예영. 의미 없이 흘러가던 그녀에게 우연 같은 필연으로 한 명이 엮인다.`,
    keywords: `#현대물 #GL #백합 #고등학생 #대학생 #교생 #선생님 #학생 #사제관계 #여름 #계절물 #사제백합`,
    links: { aladin:"http://aladin.kr/p/of3nY", ridi:"https://ridibooks.com/books/4614000018", series:"", kakao:"", kyobo:"https://m.kyobobook.co.kr/digital/ebook/ebookContents.ink?barcode=480D220115320", yes24:"http://m.yes24.com/Goods/Detail/106384265", bomtoon:"", bookcube:"https://bit.ly/3FWGcFX", joara:"" } },

  { title: "첫사랑 작동법",
    slug: "cheossarang-jagdongbeop",
    poster: `https://drive.google.com/thumbnail?id=1xZFk6RB_MNRaaEdNfCau2JmyZABroWbm&sz=s4000`,
    synopsis: `풋풋한 21학번 새내기가 된 유하연. 부푼 설렘을 안고 캠퍼스 생활을 시작했지만, 오티 날 저지른 실수로 인해 한 학년 선배인 '손예지'와 악연으로 엮여버린다.`,
    keywords: `#현대물 #GL #백합 #대학생 #신입생 #직속선배 #직속후배 #퀸카 #인기녀 #첫사랑 #삽질물 #캠퍼스로맨스`,
    links: { aladin:"http://aladin.kr/p/m4FRD", ridi:"http://naver.me/xTlbjKLA", series:"", kakao:"", kyobo:"http://m.kyobobook.co.kr/digital/ebook/ebookContents.ink?barcode=480D211216410", yes24:"http://m.yes24.com/Goods/Detail/105787379", bomtoon:"", bookcube:"https://bit.ly/3sq9Tf9", joara:"" } },

  { title: "밤과 밤",
    slug: "bam-gwa-bam",
    poster: `https://drive.google.com/thumbnail?id=1MR5FwYCVg7AhXPJ_7BdETCvxFOMgQ-e4&sz=s4000`,
    synopsis: `'친구 사이에 벌어질 수 없는 일이 벌어졌다.'\n\n친구 사이였던 지은과 유리는 키스를 하며 마음을 확인하고, 연애를 시작한다.`,
    keywords: `#현대물 #GL #백합 #대학생 #이공계 #동갑커플 #몰래연애 #비밀연애 #달달물 #캠퍼스로맨스`,
    links: { aladin:"http://aladin.kr/p/PPvg3", ridi:"https://ridibooks.com/books/4614000005", series:"", kakao:"", kyobo:"https://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?barcode=480D211119040", yes24:"http://www.yes24.com/Product/Goods/105310191", bomtoon:"", bookcube:"https://bit.ly/3xogQhf", joara:"" } },

  { title: "친구 사이에",
    slug: "chingu-saie",
    poster: `https://drive.google.com/thumbnail?id=1ZVc-bBrdphRRbqOrPzKtUzYJmLyfIbPM&sz=s4000`,
    synopsis: `자꾸만 마음에 걸리는 그 아이, 남지은. 하지만 동성이라는 이유로 호감조차 제대로 표현할 수 없는데…. 친구 사이에 만족해야 한다고 자신을 타일러도, 사람의 감정이란 뜻대로 되지 않는 법.`,
    keywords: `#현대물 #GL #백합 #대학생 #이공계 #동갑커플 #몰래연애 #비밀연애 #달달물 #캠퍼스로맨스 #첫사랑`,
    links: { aladin:"http://aladin.kr/p/14nIe", ridi:"https://ridibooks.com/books/4614000009", series:"", kakao:"", kyobo:"https://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?barcode=480D211119080", yes24:"http://www.yes24.com/Product/Goods/105310187", bomtoon:"", bookcube:"https://bit.ly/3xsai1o", joara:"" } },

  { title: "미케네의 목마",
    slug: "mikeneuui-mokma",
    poster: `https://drive.google.com/thumbnail?id=132XI_s2CtS5ZN0e5f-3ZuL0vQQ-w6you&sz=s4000`,
    synopsis: `그리스 영웅 시대의 막을 내린 트로이 전쟁. 미케네의 여왕 아에기나는 아내인 왕비 클리템네스트라에게 도끼를 맞고 죽는다. 다시 눈을 떴을 땐 자신이 죽기 10년 전으로 돌아와 있었다.`,
    keywords: `#GL #백합 #시대물 #고대 #그리스 #신화 #미케네 #트로이전쟁 #루프물 #회귀 #시간역행 #전쟁물`,
    links: { aladin:"http://aladin.kr/p/b4Nxb", ridi:"https://ridibooks.com/books/4614000002", series:"", kakao:"", kyobo:"https://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?barcode=480D210838550", yes24:"http://m.yes24.com/Goods/Detail/103649022", bomtoon:"", bookcube:"https://www.bookcube.com/detail.asp?series_num=921024943", joara:"" } },

  { title: "애집(愛執)",
    slug: "aejip",
    poster: `https://drive.google.com/thumbnail?id=1gMliwurZdfgSjnuev2hQFz_XRxqradEb&sz=s4000`,
    synopsis: `미숙했던 시절에 사랑했던 사람을 속절없이 떠나보내야 했던 현지우. 옛 상처를 추스르고 새 사랑을 시작하려는 그녀 앞에, 과거에 헤어졌던 여자, 오연아가 다시 나타났다. 그것도 최악의 형태로.`,
    keywords: `#현대물 #백합 #GL #동거 #첫사랑 #상처녀 #능력녀 #피폐물 #삼각관계 #스릴러 #전문직`,
    links: { aladin:"http://aladin.kr/p/WPH4h", ridi:"https://ridibooks.com/books/4614000001", series:"", kakao:"", kyobo:"https://digital.kyobobook.co.kr/digital/ebook/ebookDetail.ink?barcode=480D210836560", yes24:"http://www.yes24.com/Product/Goods/103303390", bomtoon:"", bookcube:"https://www.bookcube.com/detail.asp?series_num=921024943", joara:"" } }
];
